name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer
        run: |
          pip install --user --upgrade buildozer Cython==0.29.33

      - name: Build with Buildozer
        run: |
          # Isse pehle ki build shuru ho, hum zaroori system files khud install karenge
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          export PATH=$PATH:$HOME/.local/bin
          buildozer --version
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: smartwatch-app
          path: bin/*.apk
# restart build
